### ISSUE TITLE
Can't create plugin

### ISSUE THREAD

**Issue by davideprevosto** [mcguffin/wp-plugin-boilerplate#2]
Hi there,

I did try to use your scripts, but:

`$ wp-plugin "test"                                                           `

> Traceback (most recent call last):
>   File "/Users/encodia/scripts/wp-plugin", line 10, in <module>
>     import wp_plugin.plugin as p
>   File "/Users/encodia/scripts/wp-plugin-boilerplate/wp_plugin/plugin.py", line 6, in <module>
>     import wp_plugin.modules.plugin_module as m
>   File "/Users/encodia/scripts/wp-plugin-boilerplate/wp_plugin/modules/plugin_module.py", line 2, in <module>
>     import wp_plugin.file_template as f
>   File "/Users/encodia/scripts/wp-plugin-boilerplate/wp_plugin/file_template.py", line 2, in <module>
>     import sys, os, pystache, re, pwd, pprint, shutil,codecs,subprocess
> ModuleNotFoundError: No module named 'pystache'

Do you have any idea?

Thank you

**Comment by xlthlx** [comment]
Hi Davide, it seems that you don't have a Python module installed, try with 
`pip install pystache`
and then try again to create a plugin.
Please let me know if that works

Serena
